### ISSUE TITLE
Draft: Contract of the Module United Nations

### ISSUE THREAD

**Issue by ungoldman** [ungoldman/module.party#1]
## Initial Draft

Whereas the goals of this party are stated as,
1. A modular, loosely coupled, fault tolerant architecture for all,
2. Avoidance of global and environmental dependencies,

Whereas it is held self-evident that the following terms are sufficient to further said goals for the mutual benefit of all,

```
npm install
npm test
npm start
```

Whereas the practice of exceeding the above terms is deemed an anti-pattern,

We propose the adoption of the above conventions as the basis of the **Contract of the Module United Nations**.

**Comment by bcomnes** [comment]
There is a good section of the http://nodeup.com/onehundredfour interview where @feross talks about why peer dependencies are bad.  I'll try to get the excerpt when I have time or someone beats me to it.

**Comment by hackergrrl** [comment]
Awesome. :tada:    I <3 locality. I also adhere to user and state locality:

3) Default to the current user; avoid requiring superuser privileges as much as possible.

4) If your module needs to touch the file system, default to the current directory, and do not spill module state outside of it.

Maybe also

5) Avoid native dependencies where possible; this implicitly pulls in global dependencies (`gcc`, etc), and native deps are hard to version; they may not even respect semantic versioning.

Oh, and in case it's not a given:

6) Use [semantic versioning](http://semver.org/)!
