### ISSUE TITLE
Can Yarn join the party?

### ISSUE THREAD

**Issue by zeke** [ungoldman/module.party#2]
It might be cool to show the equivalent incantations for `yarn`.

```
yarn
yarn test
yarn start
```

**Comment by zeke** [comment]
Changed the title to account for multiple senses of "party".

🎉  vs ✊

**Comment by ungoldman** [comment]
sure man
verbage tbd
pr willkommen

**Comment by bcomnes** [comment]
I haven't switched over to yarn yet.  Probably should get around to that some weekend.  Ideally, we could collect this idea from more languages and set up examples for all including yarn

e.g. go

```
go get project.com/namespace/foo
cd $GOPATH/src/namespace/foo
go run
```

**Comment by zeke** [comment]
> set up examples for all

👍

**Comment by ungoldman** [comment]
i'm not as familiar with conventions outside node -- does go have something equivalent to `npm test`?

**Comment by bcomnes** [comment]
```
go test
```

**Comment by bcomnes** [comment]
It lacks the project local dependency script environment though.  That would be a neat project.

**Comment by ungoldman** [comment]
so

```
go get
go test
go run
```

?

**Comment by bcomnes** [comment]
Almost, `go get` will also git/svn/hg clone the repo into your $GOPATH src folder and built cli's and stuff, so its a bit different.  When I refresh my memory about the convention I can PR an example.  

It would be nice to generate a Rosetta Stone from lots of languages of this idea though.
