### ISSUE TITLE
`npm start` conventions

### ISSUE THREAD

**Issue by strugee** [ungoldman/module.party#3]
What are the conventions for `npm start`? Is it blocking? Or is it expected to fork a daemon into the background?

What are the conventions around this? Are there any? I don't know. Let us discuss

Personally I think this maybe doesn't matter but I'm curious what others think.

**Comment by ungoldman** [comment]
I think the convention is that `npm start` will start the program. What that means is left up to the module author. I think forking a daemon into the background is somewhat unusual.

**Comment by strugee** [comment]
> What that means is left up to the module author.

Right, that was the point of this issue. I've read http://module.party but "`npm start` starts the program" isn't really specific about what "start the program" actually means.

(To be clear when I said "is it blocking" above what I really meant was "does it execute the command in the foreground")

**Comment by strugee** [comment]
Or perhaps I'm making something out of nothing. Conventions are hard ¯\_(ツ)_/¯

**Comment by zeke** [comment]
> I think the convention is that npm start will start the program

I agree with this.

> "npm start starts the program" isn't really specific

Also true! :)

The question of running in a foreground or background process just depends on the project. Sometimes `npm start` starts a web server. Sometimes it runs a one-off script. Sometimes it runs a daemon. Sometimes it just prints usage info.

Defining `test` and `start` scripts is a polite way to make projects consistent, and to make it easier for newcomers to use your project without having to read documentation.

**Comment by ungoldman** [comment]
Well put @zeke!

@strugee sorry my answer wasn't very helpful. To add a bit of context, over the years I've seen lots of different behavior for `npm start` that make sense within the program's context. Some examples:

There are definitely some conventions for `npm start` in PaaS deployment contexts like Heroku. Usually it's expected that it starts the service (usually a server) on a port defined by the environment. Here's some related documentation: https://devcenter.heroku.com/articles/nodejs-support#runtime-behavior

However this isn't universal at all. A statically built site may not need `npm start` at all in a deployment context, so in that case I usually set `npm start` to start a local development server.

For a CLI, it would probably make sense for `npm start` to start the CLI program.

The concept of `start` doesn't have an obvious meaning for a library or framework. In those cases I think it makes sense to just leave it up to module authors what they want to accomplish, though usually I would imagine it would be something along the lines of a development server for developing/testing/iterating.

So what `npm start` will do can vary wildly. I think the expectation is that it will do *something* related to the module's core functionality, but should not be a limiting factor in defining what a node program can do.

**Comment by zeke** [comment]
> There are definitely some conventions for npm start in PaaS deployment contexts like Heroku. 

I have to take credit for that! I wrote Heroku's node buildpack to default to `npm start` in the absence of a `Procfile`
